apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-backend
  namespace: dev-backend
  labels:
    app: ms-backend
spec:
  selector:
    matchLabels:
      app: ms-backend
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-backend
    spec:
      containers:
      - name: ms-backend0
        image: python:latest
        resources:
        ports:
        - containerPort: 8880
          name: ms-backend
      - name: ms-backend1
        image: python:latest
        resources:
        ports:
        - containerPort: 8881
          name: ms-backend1
      imagePullSecrets:
      - name: docker-secret
      restartPolicy: Always
