apiVersion: v1
kind: Service
metadata:
  name: ms-backend-svc
  namespace: dev-backend
spec:
  type: NodePort
  ports:
  - name: ms-backend-svc
    port: 8000
    targetPort: 8000
    nodePort: 33331
    protocol: TCP
  selector:
      app: ms-backend-app
