apiVersion: v1
kind: Service
metadata:
  name: ms-frontend-svc
  namespace: dev-frontend
spec:
  type: LoadBalancer
  ports:
  - name: ms-frontend-svc-8883
    port: 8883
    targetPort: 8000
    protocol: TCP
  selector:
    app: ms-frontend-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend-dp
  namespace: dev-frontend
  labels:
    app: ms-frontend-dp
spec:
  selector:
    matchLabels:
      app: ms-frontend-app
  template:
    metadata:
      labels:
        app: ms-frontend-app
    spec:
      containers:
      - name: ms-frontend-app
        image: python:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      imagePullSecrets:
      - name: docker-secret
      restartPolicy: Always
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
