apiVersion: v1
kind: Service
metadata:
  name: ms-frontend-svc
  namespace: dev-frontend
spec:
  type: LoadBalancer
  ports:
  - name: ms-frontend-svc-8882
    port: 8882
    targetPort: 8000
    protocol: TCP
  selector:
    app: hello-python

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

