apiVersion: v1
kind: Service
metadata:
  name: ms-frontend-svc
  namespace: dev-frontend
spec:
  type: LoadBalancer
  ports:
  - name: ms-frontend-svc-8882
    port: 8882
    targetPort: 8000
    protocol: TCP
  selector:
    app: python

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  replicas: 4
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: python:3.9.16
        ports:
        - containerPort: 8000

