apiVersion: v1
kind: Service
metadata:
  name: ms-frontend-svc
  namespace: dev-frontend
spec:
  type: NodePort
  ports:
  - name: ms-frontend-svc-8882
    port: 8000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
  selector:
      type: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend-dp
  namespace: dev-frontend
  labels:
    app: ms-frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: ms-frontend-pod
      labels:
        app: ms-frontend-app
    spec:
      containers:
      - name: ms-frontend-app
        image: python:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Always
  replicas: 2
  selector:
    matchLabels:
      app: ms-frontend-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
